### ISSUE TITLE
ZTP IPv6 support

### ISSUE THREAD

**Issue by bencatic** [PureStorage-OpenConnect/zero-touch-provisioner#2]
I'd like to request IPv6 support for our customer KIT in Germany.

Currently you validate only against IPv4.

//validate Controller 1 Gateway
err7 := validate.Var(ct1GW.Text(), "required,ipv4")
if err7 != nil {
initResult.SetText("Please provide a valid Gateway for Controller 1")
passed = false
}

**Comment by btshowers** [comment]
Thanks Ben, I'm confirming ipv6 support in the ZTP API endpoint.  once confirmed I'll submit the update.

**Comment by ttuellmann** [comment]
I originally requested the IPv6 support. Thanks for looking into this!

**Comment by btshowers** [comment]
I've added IPV6 support to the tool and recompiled.
